# Build an image that can serve mlflow models.
FROM python:3.11.7-slim

RUN apt-get -y update && apt-get install -y --no-install-recommends nginx -y gcc g++

ARG model_dir="model_dir"

WORKDIR /opt/mlflow

# Install MLflow
RUN pip install mlflow==2.11.3


# Copy model to image and install dependencies
COPY model_dir/ /opt/ml/model
RUN python -c "from mlflow.models import container as C; C._install_pyfunc_deps('/opt/ml/model', install_mlflow=False, enable_mlserver=False, env_manager='local');"

ENV MLFLOW_DISABLE_ENV_CREATION=True
ENV ENABLE_MLSERVER=False
ENV GUNICORN_CMD_ARGS="--timeout 60 -k gevent -b 0.0.0.0:5001"

# granting read/write access and conditional execution authority to all child directories
# and files to allow for deployment to AWS Sagemaker Serverless Endpoints
# (see https://docs.aws.amazon.com/sagemaker/latest/dg/serverless-endpoints.html)
RUN chmod o+rwX /opt/mlflow/

# clean up apt cache to reduce image size
RUN rm -rf /var/lib/apt/lists/*

EXPOSE 5001
ENV SERVER_PORT 8000
ENV SERVER_HOST 0.0.0.0

ENTRYPOINT ["python", "-c", "from mlflow.models import container as C; C._serve('local')"]
